# Generated by Django 2.0.13 on 2019-04-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='exam_result_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='progress_status',
            field=models.CharField(blank=True, choices=[('결제 대기 중', '결제 대기 중'), ('출원 준비 중', '출원 준비 중'), ('심사 중', '심사 중'), ('출원공고', '출원공고'), ('거절 대응 중', '거절 대응 중'), ('등록 결정', '등록 결정'), ('등록 완료', '등록 완료'), ('갱신 대상', '갱신 대상')], max_length=80, null=True),
        ),
    ]
