# Generated by Django 2.0.13 on 2019-04-07 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OAreports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casefiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oareport',
            name='casefile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='casefiles.Casefile'),
        ),
        migrations.AddField(
            model_name='oareport',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
