# Generated by Django 2.0.13 on 2019-04-07 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_file', models.DateField(auto_now_add=True)),
                ('file_pdf', models.FileField(null=True, upload_to='')),
                ('isReportExist', models.BooleanField(default=False)),
                ('expireDate', models.DateField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, choices=[('위임 약정서', '위임 약정서'), ('상표 등록 출원서', '상표 등록 출원서'), ('의견 제출 통지서', '의견 제출 통지서'), ('등록 결정서', '등록 결정서'), ('거절 결정서', '거절 결정서'), ('상표 등록증', '상표 등록증'), ('기타 서류', '기타 서류')], max_length=80, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Case')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
